FluxML/NNlib.jl

src/NNlib.jl, src/logsigmoid.jl, test/runtests.jl
Adding `logsigmoid` which will be useful for defining the Binary Cross Entropy loss [#143](https://github.com/FluxML/Flux.jl/issues/143)
=> add logsigmoid

src/conv.jl, test/conv.jl
This closes https://github.com/FluxML/Flux.jl/issues/188
=> Add `pad` and `stride` passthroughs for conv gradients

src/conv.jl
Scalar pad and stride as suggested in issue [#235](https://github.com/FluxML/Flux.jl/issues/235) for pooling
=> Scalar pad and stride for maxpool and meanpool

src/conv.jl, src/impl/conv.jl, test/conv.jl
Added dilation support for convolution layers (2d and 3d). @staticfloat
=> Dilation support for Conv

src/impl/conv.jl, test/conv.jl
=> Fixed NaN error in dilation

src/softmax.jl, test/runtests.jl
In softmax, we first subtract element-wise maximum from the input vector to achieve better numerical stability. However, in the previous implementation it wasn't the maximum but max(0, element-wise-max).
It used to fail for `softmax([-10000, -10000.])` which should be trivial and after subtracting the max recomputed as `softmax([0, 0.])`.
P.s.: Credit should be given to Tomas Pevny for finding the precise line of the bug.
=> Fixed softmax for large negative numbers

src/linalg.jl, test/conv.jl
Fixed a few ccall parameters in gemm! function. Convolutions with Float32 type parameters work now.
=> gemm! fix for julia0.7 and julia1.0

src/impl/conv.jl
Inference has trouble with arrays, but does fine with tuples.
=> Make psize inferable

src/conv.jl
@MikeInnes Would expressing the `mode` argument work in each function call work, or do I need to add another `crosscor` function?
=> [WIP] mode parameter for Convolution/cross-convolution

src/impl/pool.jl
Fixes #87 
I tried versions using `view`s and generators but they were all slow.
=> improve performance for pooling in forward mode

src/conv.jl, src/impl/conv.jl, test/conv.jl
Added 2D transpose convolutions and tests
=> 2D Transpose Convolutions

src/conv.jl, test/conv.jl
=> allow type of x and w to differ in conv

src/impl/conv.jl
The performance gain of this PR comes mainly from identifying that the conditionals within the `im2col()` inner loops are really only needed towards the edges of the image being `im2col()`'ed.  By separating the loops into two separate segments, we are able to achieve very high memory bandwidth utilizaiton for the majority of the wallclock time of the function.  Eventually we will want to parallelize this loop via threading, but until that is possible, this should be a nice improvement. In my testing, this speeds up `im2col()` by a factor of 2-3x.
This change also begins the work of pushing some convolutional parameters into the type domain.  This is especially helpful for `im2col()`, as it makes it possible that the compiler could completely elide the second set of for loops in the case …
=> Rewrite `im2col()` for greater performance

src/impl/conv.jl
This should fix https://github.com/FluxML/NNlib.jl/pull/92#issuecomment-461834322
I have a much more thorough testing suite I'm working on that should help with this (and give us much more confidence when adding new accelerations such as NNPACK) that is based upon just writing the simple, slow, direct convolution in Julia, and then essentially fuzzing every parameter combination and comparing the outputs.
=> Fix typo in plane size calculation

src/impl/conv.jl, test/conv.jl
This patch fixes the issue of convolution breaking for filters such as (x,y) where x not equal to y. 
https://github.com/FluxML/Flux.jl/issues/700
=> Changed output size calculation to support kernel size such as (x,y)

src/pooling.jl
Using `zeros()` doesn't polymorph with `CuArrays` properly, so use `similar()` followed by `fill!()`.
=> Use `similar()` followed by `fill!()` for GPU compatibility

src/impl/conv_direct.jl
Well this is embarrassing.  On the plus side, the reference implementation is so slow it doesn't matter.  :P
=> Fix loop ordering problem in reference conv implementation

Project.toml
Since we'll be switching to Project.toml-based versioning soon, which I'm currently experimenting with for CI reasons, let's bump the version here to communicate the API breakage caused by https://github.com/FluxML/NNlib.jl/pull/94.
=> Bump version.

src/activation.jl, test/activation.jl
Added numerically stable `log(cosh(x))` https://github.com/FluxML/Flux.jl/pull/68.
=> Add `logcosh` activation

deps/build.jl
Replace the error in NNPACK build with a warning.
=> Avoid error while trying to build NNPACK on unsupported platforms

src/softmax.jl, test/activation.jl
Fixes Flux.jl issue [#744](https://github.com/FluxML/Flux.jl/issues/744#issue-435126750). `Logitcrossentropy` uses `logsoftmax` which appears to underflow for large inputs.
This issue may have been caught earlier but for what looks like an incorrect [test](https://github.com/FluxML/NNlib.jl/blob/f5fce7a9ce336e9322d98701b256e23bbb801586/test/activation.jl#L103), where the gradient of `sum(logsoftmax(xs))` where `xs` =
```julia
1.0     2.0     3.0
1000.0  2000.0  3000.0
```
is suggested to be approx. 0 for all entries. While the numerical gradient does give this for `Float32`s, I believe this is an artefact of low numerical precision. For instance, in python:
```python
import torch
xs = torch.Tensor([[1.0,2.0,3.0], [1000.0, 2000.0, 3000.0]]).requires_grad_(True)
out = …
```
=> Improve numerical stability of logsoftmax gradient

src/softmax.jl
I tried reducing the allocations for a dimension-agnostic softmax implementation but there is still a few allocations. On my pc benchmarking this against the original implementation gives very similar results however.
As for `logsoftmax`, I'm not quite sure what's happening in the original implementation so I've not yet tried to generalize that.
EDIT:
Of course, I should note I also haven't changed the derivatives yet since I'm not sure what they should be.
=> Make softmax! dimension-agnostic

src/softmax.jl, test/activation.jl
For #77, this adds a version of `logsoftmax` which takes `dims` keyword, and `∇logsoftmax` too.  
It also adjusts the implementation for `softmax` from #130 so as not to exponentiate twice; this is about twice as fast, see https://github.com/FluxML/NNlib.jl/issues/77#issuecomment-527090413 .
Both of these mutate their `out` array, which could easily be avoided if desired, at the cost of twice the memory.
=> logsoftmax with dims

src/conv.jl, src/impl/depthwiseconv_direct.jl, src/impl/depthwiseconv_im2col.jl, src/nnpack/interface.jl, src/nnpack/libnnpack.jl, src/pooling.jl, test/conv.jl
This fixes issues Flux is having right now
=> Fix asymmetric padding arguments to NNPACK's `conv()`

src/softmax.jl
Original implementation was not passing `dims` to `softmax`
I picked this up when testing gradients for FluxML/Zygote.jl#425
=> handle dims properly in gradient of logsoftmax

src/activation.jl
The current implementations of `leakyrelu`, `elu` and `selu` return `Float64` gradients for `Float32` inputs. 
```julia
julia> using NNlib, Zygote
julia> leakyrelu'(1f0)
1.0
julia> leakyrelu'(-1f0)
0.009999999776482582
julia> elu'(1f0)
1.0
julia> elu'(-1f0)
0.3678794503211975
julia> selu'(1f0)
1.0507010221481323
julia> selu'(-1f0)
0.6467686295509338
```
cf. https://github.com/FluxML/Flux.jl/issues/963. This PR is intended to preserve float precision for differentiation.
```julia
using NNlib, Zygote, Test
ACTIVATION_FUNCTIONS = [σ, relu, leakyrelu, elu, gelu, swish, selu, softplus, softsign, logcosh];
function test_deliv_float_precision_preserving(a)
@testset "$(a): " begin
for T in [Float32, Float64]
for val in [-10, -1, 0, 1, 10]
val = @inferred a'(T(val))
@test typeof(val) == T
end
end …
```
=> Preserve the type in differentiation

Manifest.toml
CI cuilds for julia:nightly are falling because of https://github.com/JuliaLang/julia/pull/34611 (Requires.jl uses the deprecated function `@get!`). Requires.jl need to be updated to 1.0.1 to pass CI tests.
It would fix the build errors of https://github.com/FluxML/NNlib.jl/pull/165 https://github.com/FluxML/NNlib.jl/pull/162.
=> Update deps for CI

Project.toml, src/activation.jl, test/activation.jl
- Add mish (https://github.com/FluxML/NNlib.jl/pull/145) to the list of the activation functions
- Type stability test for gradients (https://github.com/FluxML/NNlib.jl/pull/149)
I slightly modified the definition of `gelu` because the previous definition didn't pass the gradient test in Julia 1.0 and 1.1. (https://travis-ci.org/matsueushi/NNlib.jl/builds/643663660?utm_medium=notification&utm_source=github_status)
It is related to `pi` and I found a similar issue. https://github.com/JuliaMath/Calculus.jl/issues/144
=> Update test cases of activation functions

src/conv.jl
With `ENV["JULIA_DEBUG"] = "all"`, the string for this `@debug` fails like this:
```
┌ Error: Exception while generating log record in module NNlib at /Users/me/.julia/packages/NNlib/3krvM/src/conv.jl:97
│   exception =
│    UndefVarError: front_name not defined
│    Stacktrace:
│     [1] macro expansion at ./logging.jl:319 [inlined]
│     [2] #∇conv_data!#84(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(∇conv_data!), ::Array{AbstractFloat,5}, ::Array{AbstractFloat,5}, ::Array{Float32,5}, ::DenseConvDims{3,(5, 1, 1),16,24,(1, 1, 1),(0, 0, 0, 0, 0, 0),(1, 1, 1),false}) at /Users/me/.julia/packages/NNlib/3krvM/src/conv.jl:97
```
After:
```
julia> main()
Float32[2.9545236e32 2.9545236e32 2.9545236e32 2.9545236e32 2.9545236e32 2.9545236e32 2.9545236e32 …
```
=> Fix debug string

src/impl/conv_direct.jl, test/conv.jl
Fixes #156, https://github.com/FluxML/Flux.jl/issues/978
```julia
julia> using Flux
julia> using Flux: ConvTranspose, conv_transpose_dims
julia> using NNlib: ∇conv_data_im2col, ∇conv_data_direct
julia> ct = ConvTranspose((2, 2, 2), 4=>5, stride=2)
ConvTranspose((2, 2, 2), 4=>5)
julia> mat = Float32.(rand(16, 16, 16, 4, 3));
julia> ∇conv_data_im2col(mat, ct.weight, conv_transpose_dims(ct, mat)) |> size
(32, 32, 32, 5, 3)
julia> ∇conv_data_direct(mat, ct.weight, conv_transpose_dims(ct, mat)) |> size
(32, 32, 32, 5, 3)
```
=> Fix output shape of ∇conv_data_direct!

src/conv.jl, src/pooling.jl, src/softmax.jl
- Add missing docstrings to some "interface" functions. 
- (hopefully) improve softmax and logsoftmax documentation. 
Still many exported functions are not documented, but that will have to wait for a future PR. 
Related to https://github.com/FluxML/Flux.jl/pull/1041
=> add some docstrings

src/activation.jl, test/activation.jl
Added the following activation functions along with tests
- hardsigmoid and hardtanh are piecewise linear approximations and computationally effiecient than their counterparts, sigmoid and tanh respectively
- Threshold relu is used in Autoencoders as Threshold gated RELU
- LiSHT: Non-Parametric Linearly Scaled Hyperbolic Tangent Activation Function
Ref: https://arxiv.org/pdf/1901.05894.pdf
=> Added some Activation functions

src/batched/batchedadjtrans.jl, src/batched/batchedmul.jl, test/batchedmul.jl
This adds a simple fallback method for `batched_mul!`. 
It also narrows the signature of the methods from #100. I am not entirely sure that `StridedArray` is correct here, perhaps it should be `Array`? But for instance `using FillArrays; batched_mul(rand(3,3,3), Fill(1.0, 3,3,3))` used to be accepted, and give an error.
=> Add fallback batched_mul!

src/activation.jl, test/activation.jl
Some of activation functions defined in NNlib are incomplatible with GPU and they need `@cufunc` wrappers, which are defined in CuArrays.jl. https://github.com/JuliaGPU/CuArrays.jl/issues/614 
I found some activation function we added recently (e.g. `celu`) are GPU-unfriendly. I already submitted a PR https://github.com/JuliaGPU/CuArrays.jl/pull/615 to fix this issue, but I think it is better for us to consider GPU compatibility when we add a new function or update its definition  in future.
=> Add comment for wrapper functions in CuArrays.jl 

src/softmax.jl, test/activation.jl
Added tests for softmax variants that mutate their inputs. These make sure that the mutating variants are consistent with the default softmax functions.
PS: As a side note,  I noticed that `∇logsoftmax!` was defined as
```julia
∇logsoftmax!(Δ, xs) = ∇softmax!(Δ, Δ, xs)
```
Is there supposed to be an analogous `∇logsoftmax!(Δ, Δ, xs)`, or is this intentional?
=> Mutating softmax tests

src/activation.jl, test/activation.jl
Simpler, more accurate implementation of sigmoid.
Fix https://github.com/FluxML/NNlib.jl/issues/78
I benchmarked this and there is no performance difference.
After this PR:
```
julia> ForwardDiff.derivative(σ, -710)
4.47628622567513e-309
julia> x = 7.0; @btime σ($x);
12.757 ns (0 allocations: 0 bytes)
julia> x = -7.0; @btime σ($x);
13.704 ns (0 allocations: 0 bytes)
```
Before this PR:
```
julia> ForwardDiff.derivative(σ2, -710)
NaN
julia> x = 7.0; @btime σ($x);
13.906 ns (0 allocations: 0 bytes)
julia> x = -7.0; @btime σ($x);
13.366 ns (0 allocations: 0 bytes)
```
=> fix sigmoid

src/nnpack/NNPACK.jl
This should fix issue #200 .
With this patch I have the following results for the convolution:
```bash
for i in 1 2 4 8; do 
NNPACK_CPU_THREADS=$i julia --eval "using NNlib; @show Int(NNlib.NNPACK_CPU_THREADS); @time NNlib.conv(zeros(Float32,200,200,100,50),ones(Float32,4,4,100,100));"
done
```
```
Int(NNlib.NNPACK_CPU_THREADS) = 1
7.966892 seconds (508.67 k allocations: 1.494 GiB, 0.44% gc time)
Int(NNlib.NNPACK_CPU_THREADS) = 2
4.303962 seconds (508.67 k allocations: 1.494 GiB, 0.81% gc time)
Int(NNlib.NNPACK_CPU_THREADS) = 4
3.020974 seconds (508.67 k allocations: 1.494 GiB, 1.14% gc time)
Int(NNlib.NNPACK_CPU_THREADS) = 8
2.539355 seconds (508.67 k allocations: 1.494 GiB, 1.37% gc time)
```
=> fix allocate_threadpool when NNPACK_CPU_THREADS is set

.travis.yml, Manifest.toml, Project.toml, appveyor.yml, src/conv.jl, src/dim_helpers/PoolDims.jl, src/impl/pooling_direct.jl, src/nnpack/impl.jl, src/nnpack/interface.jl, src/pooling.jl, test/conv.jl, test/inference.jl, test/perf/Manifest.toml, test/perf/perf_report.jl, test/pooling.jl
maxpool tests are currently failing due to some type conversions. We didn't catch this since the tests were added in #207 at the same time of #204 . 
Removing the type casts I got the tests passing, but then #210 convinced me to bypass NNPACK's maxpool entirely as it is not completely reliable. 
I also, added NNPACK's conv gradient as defaults, for some reason only the forward was used before (@dhairyagandhi96 @MikeInnes @avik-pal @staticfloat do you know why?)
So, this PR does the following.
- use NNPACK only for Float32 operations, fallback to NNlib for Float64
- use NNPACK for conv gradient  
- don't use NNPACK for maxpool as a workaround for #210. Notice that NNPACK doesn't offer a gradient for maxpool, so the damage is a little mitigated.
=> updates for NNpack

src/impl/conv_im2col.jl
When dealing with padded regions in `im2col!`, loops in `if` branches are not needed in their current form, as they don't affect anything.
And it seems, like outer loops cover all `out_of_bounds` cases, if I understand correctly.
=> Remove redundant loops

Project.toml, src/NNlib.jl, src/activation.jl, src/softmax.jl
Following discussion in FluxML/Flux.jl#1272, #224, it is best to have a better pattern to introduce vectorisation in a more formal manner.
This reverts #199 for the time being.
=> Revert LoopVectorization

src/impl/conv_im2col.jl, src/impl/depthwiseconv_im2col.jl
Fixes issue #197.
The issue is caused by threading, and if `JULIA_NUM_THREADS` is greater than 1, it can be reproduced with the following MWE, which compares the gradients computed with `∇conv_filter_im2col` to those computed with `∇conv_filter_direct`.
```julia
using NNlib, Random
function compare_grad()
Random.seed!(0)
x = rand(50,1,10)
w = rand(3,1,1)
dy = rand(50,1,10)
cdims = DenseConvDims(size(x), size(w); stride=1, padding=1)
dw1 = NNlib.∇conv_filter_im2col(x, dy, cdims)
dw2 = NNlib.∇conv_filter_direct(x, dy, cdims)
maximum(abs, dw1-dw2)
end
```
In a correct implementation, `compare_grad()` should always return zero. Since the random seed is set to zero, the result should also be deterministic. However, when using multithreading it returns seemingly random large numbers:
```julia …
```
=> Fix multithreading bug in ∇conv_filter_im2col

src/conv.jl
Uses maxlog=1 to limit the @warn logging.
#232
=> Limit logging of fallback @warning 'maxlog=1'

.gitignore, src/impl/pooling_direct.jl, test/pooling.jl
This fixes the errors returned by `meanpool` on edges. 
Core issue was that a `max(m, 0)` was applied to both mean and max pooling for padded elements. Instead, no operation should be performed for meanpool. 
For example, currently: 
```julia
julia> x = ones(Float32,4,4,1,1) .* -1
[:, :, 1, 1] =
-1.0  -1.0  -1.0  -1.0
-1.0  -1.0  -1.0  -1.0
-1.0  -1.0  -1.0  -1.0
-1.0  -1.0  -1.0  -1.0
julia> pool = meanpool(x, PoolDims(x,2,padding=1))
3×3×1×1 Array{Float32,4}:
[:, :, 1, 1] =
-0.25  -0.25  0.0
-0.5   -1.0   0.0
0.0    0.0   0.0
julia> pool = meanpool(CuArray(x), PoolDims(x,2,padding=1))
3×3×1×1 CuArray{Float32,4}:
[:, :, 1, 1] =
-0.25  -0.5  -0.25
-0.5   -1.0  -0.5
-0.25  -0.5  -0.25
```
With this fix, the base cpu version now results in the same value. A test has been added. 
There's the …
=> fix meanpool bug #229

Project.toml, src/batched/batchedadjtrans.jl, src/batched/batchedmul.jl, src/gemm.jl, test/batchedmul.jl
This is an alternative to #187. 
It similarly allows `batched_mul` to work on many `PermutedDimsArray`s, but does this just by calling `strides(A)` and branching. It also extends `batched_mul!` to take `α, β` scales like `mul!`.
It adds two functions `storage_type` and `is_strided`, both of which recursively unwrap things. This avoids trying to dispatch on `BatchedAdjoint{PermutedDimsArray{...,CuArray}}`... instead it can separately check the underlying storage, and whether it should be safe to call `strides(A)`.
It also improves `batched_gemm!` to multi-thread the batch index (using https://github.com/JuliaLang/julia/pull/36360 to save & restore the number of BLAS threads), and to allow `size(A,3)==1` (batch only B,C).
=> Allow batched_mul to work through PermutedDimsArray, II

src/batched/batchedmul.jl, src/gemm.jl, test/batchedmul.jl
This adds:
* multi-threading via `Threads.@spawn`, which is disabled for very small problems
* methods `batched_mul(::Array{T,3}, ::Matrix)` which reshape to a 3-array
* unicode alias `⊠` for infix use
* a function `batched_vec(::Array{T,3}, ::Matrix)` which reshapes so that the matrix is a batch of vectors
* more detailed docstrings.
I've marked it draft as it refers to things being added here: https://github.com/JuliaMath/TensorCore.jl/pull/1. But that could be removed for now.
=> Improvements to `batched_mul`

src/softmax.jl, test/softmax.jl
1. What about add a inplace version of softmax, with `dims` parameter?
2. `softmax` is updated too, this can reduce memory usage by 40%.
note:
The memory uses of `softmax!` is the same as the old `softmax`.
The performance does not change.
=> added softmax!. reduced softmax's memory usage.

src/activations.jl
Follow up from #257 I think we should do this for all ADs,
and so the TODO shouldn't be there.
AFAICT, this code is basically just hand-unrolling what the AD would ideally do on its own.
So at worst it has basically no effect except maybe to reduce compile-time slightly.
We are talking about doing something like this for a whole bunch of scalar functions in ChainRules.
https://github.com/JuliaDiff/ChainRules.jl/issues/222
@willtebbutt what do you think?
=> Remove TODO about not defining broadcasted for ADs other than Zygote

src/activations.jl, test/activations.jl
~~We do a lot of wasteful divisions in the effort of being type stable with integer inputs, something which we don't really care about. 
With this PR we still support integer inputs but we focus on Float32 and Float64 performances.
I remove all those `x/1` divisions and  `oftype(x/1, someconstant)` conversions.
As a result, the code is also much nicer. 
This PR is breaking for integer inputs and also disrespectful of Float16, since all constants are now Float32. 
We should benchmark  before merging (if we want to merge)
This PR makes some of the function type-unstable with integer inputs~~
- Fix the hardsigmoid definition, not matching the cited paper, so that now it matches the pytorch definition.
- Replace the occurrencies of `x / 1`  with `float(x)` for clarity
=> fix hardsigmoid and use float(x) instead of x/1 

Project.toml, src/upsample.jl, test/pooling.jl, test/upsample.jl
Sorry to bother you again! But this stuff didn't let me sleep, so here is a CPU implementation. See [GPU PR](https://github.com/JuliaGPU/CUDA.jl/pull/636) here.
I reviewed the tests of the current implementation and found it a bit strange, actually. So this one comes with a bit different tests.
Mean benchmark times in ms, upsampling by a factor of 2,
tested on 12 threads @3.7Ghz, julia 1.7
32x32x1024x1
|   | before  | after  |
|---|---|---|
| forward  | 53  | 2.7  |
| backward  | 94  |  0.8 |
196x196x128x1
|   | before  | after  |
|---|---|---|
| forward  | 318  | 21  |
| backward  | 64  |  3.6 |
single threaded:
32x32x1024x1
|   | before  | after  |
|---|---|---|
| forward  | 50  | 27  |
| backward  | 71  |  7.5 |
196x196x128x1
|   | before  | after  |
|---|---|---|
| forward  | 300  | …
=> improve bilinear upsampling

src/upsample.jl
This was a commit of #269 which got reverted so as not to cause chaos.
Should have no functional changes. Code for `pixel_shuffle` is altered to remove `@assert`.
=> Upsample docstring improvements

src/NNlib.jl, src/padding.jl, test/padding.jl, test/runtests.jl
Maybe not the most optimized implementation, but it is simple, generic, AD and gpu friendly.
Other padding modes should not be too hard to implement similarly 
cfr. https://pytorch.org/docs/stable/nn.html#padding-layers
=> add pad_constant, pad_repeat, pad_reflect, pad_zeros

.github/workflows/ci.yml, src/padding.jl, test/padding.jl
We should clean up the dimension handling - which needs the extra `gen_pad` which uses arrays in some cases. We can get rid of those, I think.
```Julia
julia> @btime NNlib.pad_constant($r, (2,2,2,2,0,0,0,0));
558.871 ns (5 allocations: 1.06 KiB)
julia> @btime NNlib.pad_constant($r, (2,2,2,2,0,0,0,0));
1.644 μs (29 allocations: 2.45 KiB)
```
=> Faster constant padding

Project.toml, src/NNlib.jl, src/gather.jl, src/scatter.jl, test/gather.jl, test/runtests.jl
easiest part of #255 
@yuehhua
=> add gather

src/padding.jl, test/padding.jl
This PR fixes #293 and #294, and in the process moves to using only `((l1, r1), ..., (ln, rn))` representation of padding internally instead of both that and `(l1, r1, ..., ln, rn)`. This means that we can simplify the codebase a bit.
=> Fixes #293 and #294

lib/NNlibCUDA/LICENSE.md
Each subdirectory package needs to have its own copy of the license file. This is because when we distribute tarballs (e.g. via the Pkg server), the tarball only includes the subdirectory package. So we need to make sure that the subdirectory has a license; otherwise, the tarball won't have a license.
cc: @CarloLucibello
=> Add a `LICENSE.md file` for the `NNlibCUDA.jl` package

Project.toml, src/batched/batchedadjtrans.jl
Add adapt rules for the batch wrappers.
Usually you are not supposed to ever see the batched_* wrappers but they make some unfortunate appearance in second derivatives.
```julia
using NNlib, Zygote, CUDA
W = rand(Float32, 1, 1, 2) |> cu
x = rand(Float32, 1, 1) |> cu
function ftest(W)
gz, back = Zygote.pullback(x -> NNlib.batched_mul(W, x), x)
back(gz)[1]
end
y, back = Zygote.pullback(ftest, W)
back(y)[1]
```
without adapt rule:
```
ERROR: GPU compilation of kernel broadcast_kernel(CUDA.CuKernelContext, CuDeviceArray{Float32,3,1}, Base.Broadcast.Broadcasted{Nothing,Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}},typeof(Zygote.accum),Tuple{Base.Broadcast.Extruded{CuDeviceArray{Float32,3,1},Tuple{Bool,Bool,Bool},Tuple{Int64,Int64,Int64}},Base.Broadcast.Extruded{NNlib.BatchedAdjoi …
```
=> Adapt rules for batched_* wrappers

src/utils.jl
Existing implementation use scalar indexing for cuarray. To avoid using scalar indexing, refactoring is done.
=> Avoiding scalar indexing in cuda

.github/workflows/ci.yml, Project.toml, test/runtests.jl
Best to test with released NNlibCUDA now that its registered.
=> Add NNlibCUDA to test deps

src/upsample.jl, test/upsample.jl
Hi everybody!
This introduces trilinear (3D) upsampling on GPU. Maybe we can rethink the dispatch; I think the code can be deflated by smart choices.
=> introduce trilinear upsampling

Project.toml, src/activations.jl, src/conv.jl, src/gather.jl, src/padding.jl, src/pooling.jl, src/scatter.jl, src/upsample.jl, src/utils.jl, test/runtests.jl, test/scatter.jl, test/test_utils.jl
Fix #317. The main problem was in the use of FiniteDifferences' central difference method on singularities of non-smooth functions.
=> scatter cleanup and fix min/max

src/upsample.jl, test/upsample.jl
Hi! This introduces linear upsampling along the first dimension of a 3D array. GPU PR will follow. Again, this adds duplicate code - either I can work longer on this PR and boil it down or in a subsequent PR, as you like it.
Edit: Breaking tests *seem* unrelated :)
=> introduce linear upsampling

src/utils.jl, test/utils.jl
related to #326.
Fix commit of "fix gradient of scatter for mean" in FluxML/NNlibCUDA.jl#13
I add some tests for it.
=> Support reverse_indices for integer, tuple, CartesianIndex index

src/utils.jl, test/utils.jl
Solve the issue related to FluxML/NNlibCUDA.jl#13.
`CartesianIndex` itself is not sufficient, but `CartesianIndex{N}` is the full type.
A full type is required to convert an object into cuarray and pass it into a cuda kernel.
At the same time, I am considering making an `reverse_indices` API for cuda.
=> Fix the output type of reverse_indices

src/gather.jl
Fixed the issue encountered in https://github.com/FluxML/Flux.jl/pull/1516
https://github.com/FluxML/Flux.jl/pull/1516#issuecomment-877762749
Annoyingly, tests for this should go into NNlibCUDA, so I guess I won´t add tests for the time being.
We should reconsider having NNlibCUDA as a subpackage #300
=> gather shouldn't fallback to getindex

src/conv.jl, src/dim_helpers/ConvDims.jl, src/dim_helpers/DenseConvDims.jl, src/padding.jl, test/conv.jl, test/padding.jl, test/runtests.jl, test/test_utils.jl
Also propagate it to the kernel calls.
=> Support groups in DenseConvDims

src/activations.jl, test/activations.jl
This proposes to add faster, lower-precision, versions of `tanh` and friends. Motivation:
```julia
julia> @btime x * x   setup=(x=randn(Float32,100,100));
20.250 μs (2 allocations: 39.11 KiB)  # mac M1, julia 1.7 + rosetta
52.718 μs (2 allocations: 39.11 KiB)  # xeon E5-2603
julia> @btime y .= tanh.(x * x)   setup=(x=randn(Float32,100,100); y=similar(x));
107.167 μs (2 allocations: 39.11 KiB)
229.725 μs (2 allocations: 39.11 KiB)
julia> @btime y .= tanh_faster.(x * x)   setup=(x=randn(Float32,100,100); y=similar(x));
27.125 μs (2 allocations: 39.11 KiB)
67.623 μs (2 allocations: 39.11 KiB)
```
There has been talk of using LoopVectorization to speed this up instead. At least for the computers I tried, this lower-precision function is faster. Of course that may speed up other things, but …
=> Add faster `tanh` implementation(s)

Project.toml, src/NNlib.jl, src/sampling.jl, test/conv.jl, test/runtests.jl, test/sampling.jl
This PR adds [grid sampling](https://pytorch.org/docs/stable/generated/torch.nn.functional.grid_sample.html) for the 4D case.
This is needed for things like self-supervised depth estimation, where a neural network would learn a depth `D` for the current image and projection transformation `P` for the adjacent images and does "warping" of the images using `D` and `P`.
And this function does image sampling given projected coordinates (a.k.a. `grid`).
The implementation differs from the PyTorch's version in that it assumes `align_corners = True` and uses only bilinear interpolation. It was tested to give the same results as PyTorch's version.
[PR](https://github.com/FluxML/NNlibCUDA.jl/pull/31) with the CUDA kernels.
=> Add grid sampling

src/impl/depthwiseconv_direct.jl, test/conv.jl
There was a silly typo bug in the direct depthwise convolution algorithm
that broke multi-channel testsets.  Perhaps more disturbingly, our
default test set did not catch this, because multi-channel workloads are
not run unless the fuzzing tests are run.
=> Fix direct Depthwise convolution implementation

README.md
We are not using travis and appveyor anymore. The day we will have solved the CI issues we could add a github actions CI badge
=> remove CI badges

Project.toml, src/activations.jl
As noted here https://github.com/FluxML/NNlib.jl/pull/371#issuecomment-1011411925 defining as a fallback only `tanh_fast(::Real)` causes problems for Flux right now. And `tanh` of course makes sense for complex numbers.
But really, all the other activation functions only make sense for real numbers, since they often compare `x>0` etc. In the interests of sanity and sensible guard-rails, they should probably all have signature `::Real` not `::Any`. But can't be changed just yet.
=> Widen `tanh_fast` signature

src/softmax.jl
This PR fixes #373 by adding a warning saying that `softmax` expects an array and not a number.
=> Informative error message for softmax variants

src/scatter.jl
It is easy to forget about this [performance tip](https://docs.julialang.org/en/v1/manual/performance-tips/#Be-aware-of-when-Julia-avoids-specializing)
With this PR we get a >100x speedup by triggering specialization on `op`  :exploding_head: 
```julia
using Random, NNlib, BenchmarkTools
n = 100
m = 500
idx = rand(1:n, m)
src = rand(m)
dst = zeros(m)
@btime NNlib.scatter!(+, d, $src, $idx)  setup=(d=copy($dst));
```
Related to https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/124  cc @learning-chip
=> trigger op specialization in scatter

src/conv.jl, test/conv.jl
``gradtest`` for ``sum(∇conv_filter(x, y, cdims))`` sometimes failing for 3d convolutions.
=> add `rrule(::typeof(∇conv_filter)`

src/conv.jl
This avoids: 
```
┌ Warning: Slow fallback implementation invoked for conv!  You probably don't want this; check your datatypes.
[183](https://github.com/FluxML/Flux.jl/runs/5079634118?check_suite_focus=true#step:6:183)
│   yT = ForwardDiff.Dual{Nothing, Float32, 8}
[184](https://github.com/FluxML/Flux.jl/runs/5079634118?check_suite_focus=true#step:6:184)
│   T1 = ForwardDiff.Dual{Nothing, Float32, 8}
[185](https://github.com/FluxML/Flux.jl/runs/5079634118?check_suite_focus=true#step:6:185)
│   T2 = Float32
[186](https://github.com/FluxML/Flux.jl/runs/5079634118?check_suite_focus=true#step:6:186)
└ @ NNlib ~/.julia/packages/NNlib/JQe1Z/src/conv.jl:288
[187](https://github.com/FluxML/Flux.jl/runs/5079634118?check_suite_focus=true#step:6:187)
```
You will still get the warning if you mix …
=> Silence some warnings

src/NNlib.jl, src/gemm.jl
Xref https://github.com/JuliaLang/julia/pull/44360, `libblas` is not used anymore for Julia v1.9 and above, and `libblastrampoline` is instead. Causing errors for CI on Julia master including places like https://github.com/FluxML/Metalhead.jl/pull/125#issuecomment-1055716157
=> Change libblas to libblastrampoline

.buildkite/pipeline.yml, .github/workflows/Downstream.yml, .github/workflows/ci.yml, Project.toml, src/deprecations.jl, src/softmax.jl, test/softmax.jl
This should make softmax twice-differentiable. The code in `∇softmax` is simple enough not to bother writing a gradient by hand, all that's needed is not to take the mutating path. (Wasn't there an issue about this?)
While I'm less sure this is a good idea, it also removes `∇softmax!` entirely. That should mean that for CuArrays, it will avoid the slow path described here: https://github.com/FluxML/NNlibCUDA.jl/issues/30
Third, it also moves the old `∇softmax(Δ, x)` deprecations.jl, and adds a warning. I see this is still in use by Tracker, https://github.com/FluxML/Tracker.jl/blob/master/src/lib/array.jl#L474, but that can be fixed.
Finally, it adds a note about use with Flux, thus closes #372.
=> Simplify `softmax`, test second derivatives

.buildkite/pipeline.yml, Project.toml, src/activations.jl, test/runtests.jl
This avoids using rational numbers in some activation function gradients, as that causes problems on GPU. 
Closes #398, closes #400.
=> Avoid `Rational` in activation function gradients

Project.toml, src/activations.jl, test/activations.jl
=> Fix `tanh_fast` for large Float64

src/upsample.jl
Hi! Sorry once again for the mess I caused. This PR here cleans it up a bit and implements the suggestion from @mcabbott https://github.com/FluxML/NNlib.jl/pull/410#issuecomment-1142419044 to add another step of dispatch. Most of the code reductions still apply. The newly added block of forwarding can be removed at the next breaking change and the functions be renamed. NNlibCUDA can freely overload either e.g. `upsample_linear_kernel` or `upsample_linear_wcn`; the corresponding PR does exactly that and switches from the latter to the former. I tested both, NNlibCUDA v0.2.3 and the branch against this PR and both works.
=> partly revert changes to stay compatible w NNlibCUDA

src/upsample.jl, test/upsample.jl
The current implementation uses the array input type to convert width/height/.... which creates non-real numbers when the input is complex. This fixes it by using the real type.
=> support complex input for upsample

src/activations.jl, test/activations.jl
An attempt to fix #422...hopefully this doesn't break anything
=> Define activation functions taking arrays as input

src/batched/batchedadjtrans.jl
This make `batch_transpose` or `batch_adjoint` over gpu array broadcastable.
without this patch:
```julia
julia> using NNlib, CUDA
julia> x = cu(randn(3,4,1));
julia> CUDA.allowscalar(false)
julia> batched_transpose(x) + batched_transpose(x)  
ERROR: Scalar indexing is disallowed.
Invocation of getindex resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore are only permitted from the REPL for prototyping purposes.
If you did intend to index this array, annotate the caller with @allowscalar.
Stacktrace:                                                
[...]
```
with this patch:
```julia
julia> using NNlib, CUDA
julia> x = …
```
=> make BatchedAdjOrTrans return correct BroadcastStyle

Project.toml, src/NNlib.jl, src/ctc.jl, test/ctc.jl, test/runtests.jl
=> Move `ctc_loss` from Flux to NNlib

src/activations.jl, test/activations.jl
In something like `relu.(x .+ b)`, the broadcast rule for `.+` in Zygote always makes an array, but the rule in ChainRules makes a `Broadcasted` to permit fusion. In that case the rule for `relu.(x::Numeric)` here won't currently be called; so this PR widens its signature. As suggested here: https://github.com/FluxML/NNlib.jl/issues/432#issuecomment-1214444303
=> Widen activation broadcast rules

.buildkite/pipeline.yml, .gitignore, benchmark/Project.toml, benchmark/benchmarks.jl, benchmark/runbenchmarks.jl
A revamp of @dfdx's work in #304. The main changes here are running benchmarks and rendering the report on Buildkite instead of GHA, because the former gives us runners with >2 threads.
- ~~Tests are added~~
- ~~Documentation, if applicable~~
=> Add basic benchmark harness

.github/workflows/TagBot.yml, docs/Project.toml
See https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249
We don't want it running every hour to check if a new version of NNlib was released. Environment-friendly and efficient.
> **Warning**
> This should be merged after a new release (triggered here - https://github.com/FluxML/NNlib.jl/commit/a5e51ab634eac8f2a748312b8f3d872a8c0d3ffe#commitcomment-87743155) is created by the TagBot in the next run. Should happen roughly in the next 20 minutes.
=> Trigger tagbot on issue comments

src/dim_helpers/ConvDims.jl, src/impl/conv_im2col.jl, src/impl/depthwiseconv_im2col.jl, test/conv.jl
This should hopefully fix persistent threading-related issues on CI, While also slightly reducing memory usage when taking gradients. The fix applied is the same as https://github.com/FluxML/NNlib.jl/pull/235. I've taken the opportunity to not over-allocate memory for convs and depthwise convs at the same time.
Fixes https://github.com/FluxML/NNlib.jl/issues/359, which has been causing CI failures for the past two years...
=> Remove threading from all `∇*conv_filter` and re-enable old tests

docs/src/reference.md, src/NNlib.jl, src/fold.jl, test/fold.jl, test/runtests.jl
Added `fold` / `unfold` operators for [pytorch feature parity](https://github.com/FluxML/Flux.jl/issues/1431). These are useful for nonlocal operators in convnets. I tried to follow a similar style as `conv` and `meanpool`, and similar argument structuring as [pytorch's fold/unfold](https://pytorch.org/docs/stable/generated/torch.nn.Unfold.html#torch.nn.Unfold). 
I initially looked at pull #303 but ended up writing things a little differently.
I have not had the chance to test on GPU yet, but can give it a go soon.
Feedback is greatly appreciated!
=> Add fold and unfold

src/gather.jl, test/gather.jl
=> add `gather(src,  IJK...)`

src/softmax.jl
I think `max` is very careful about NaN & signed zero, and hence `maximum` is surprisingly slow. This uses the `@fastmath` version: 
```
julia> let x = randn(Float32, 100, 1000)
@btime softmax($x)
@btime _softmax($x)  # this PR
end;
min 1.344 ms, mean 1.422 ms (7 allocations, 398.91 KiB)
min 647.875 μs, mean 707.579 μs (3 allocations, 394.73 KiB)
```
=> Avoid `maximum` in `softmax`

docs/src/reference.md
Documenter reports missing docstrings because these were included sans prefix despite not being exported.
- [N/A] Tests are added
=> Fixup docs for fold and unfold

src/softmax.jl
=> `fast_maximum` also for `logsumexp`

Project.toml, src/NNlib.jl, src/dropout.jl, test/dropout.jl, test/runtests.jl
This adds a `dropout` function.
At least on CPU, this should be about twice as fast as the one in Flux, and use less memory. There are some Flux PRs, but the code is messy, and I got lost & started from scratch.
It's not quite the fastest variant. The gradient can be faster if we believe that every zero in the output comes from the mask, never from the input. That may not be a terrible assumption -- if you don't have a `relu` before it, zeros are rare; if you do, then the gradient associated to a zero will be discarded anyway. But... perhaps it's best to be correct.
<details>
I can put a gist of these variations somewhere. But local benchmarks are:
```julia
let x = randn(Float32, 100, 100)
@btime dropout($x, 0.3) # Flux
@btime mydropout($x, 0.3)  # sans mask -- this PR
@btime …
```
=> Add `dropout`

Project.toml, docs/src/reference.md, src/NNlib.jl, src/softmax.jl, src/utils.jl, test/runtests.jl, test/utils.jl
Motivated by https://github.com/FluxML/Tracker.jl/issues/133
Possibly it could have a better name, but what?
=> Add `within_gradient`

docs/src/reference.md, src/NNlib.jl, src/dim_helpers/PoolDims.jl, src/impl/pooling_direct.jl, src/pooling.jl, test/perf/perf_report.jl, test/pooling.jl
About FluxML/Flux.jl#1431: LPPool1d and LPPool2d.
Related tests and documentation will come soon.
=> Add `lppool` implementation

src/batched/batchedmul.jl
Branching on the type of the second argument in `batched_vec` caused a subtle performance bug when differentiating via `Zygote`.
Fixes #462.
=> Refactor `batched_vec`

src/pooling.jl
---
I try to add type conversion. But I find `x^p (typeof(p) <: Integer)` is a little slower than `x^p (typeof(p) == Float32)`:
```julia
a = 1:4000000
b = convert(UnitRange{Float32}, a)
@time for i in a
lpnormpool(ones(Float32, 4,1,1), i, (2,), stride=1)
end
@time for i in b
lpnormpool(ones(Float32, 4,1,1), i, (2,), stride=1)
end
```
Result:
```text
9.858444 seconds (96.00 M allocations: 5.662 GiB, 2.62% gc time) # a
8.916446 seconds (96.00 M allocations: 5.603 GiB, 2.95% gc time) # b
```
I also change calling sequence:
```text
8.995194 seconds (96.00 M allocations: 5.603 GiB, 2.99% gc time) # b
9.866587 seconds (96.00 M allocations: 5.662 GiB, 2.73% gc time) # a
```
Does this mean `x^p (p::Integer)` is slower than when p is a float? or I make some mistakes when testing?
=> Reduce `lpnormpool` unnecessary conversion

docs/src/reference.md, src/NNlib.jl, src/padding.jl, test/padding.jl
Implements and exports `pad_symmetric` and `pad_circular`, addressing #463. Implemented padding is consistent with [ImageFiltering.jl](https://juliaimages.org/ImageFiltering.jl/stable/function_reference/#Boundaries-and-padding).
=> symmetric and circular padding

src/conv.jl, test/conv.jl
Fixing https://github.com/FluxML/NNlib.jl/issues/369.
When the convolution filter type is not the same as the input array, **conv** uses the _direct_ backend
Probably this backed was not updated when grouped convolution was added to **conv**, which led to some false warnings about dimension mismatches given that the **check_dimension** function changed as well.
This PR adds the same logic used in _im2col_ backend to the _direct_ backed, so grouped convolutions also works for the _direct_ backend.
Now for both _conv_ and _depthwiseconv_ (and their forwarding definitions), we have the functions definitions of both im2col and direct backend in a for-loop.
The idea is that future features or corrections will always be implemented for both backends avoiding the problem that happened in …
=> Fix conv with groups when falling in direct backend

.buildkite/pipeline.yml, Project.toml, docs/src/index.md, ext/AMDGPUExt/AMDGPUExt.jl, ext/AMDGPUExt/activations.jl, ext/AMDGPUExt/conv.jl, ext/AMDGPUExt/pool.jl, ext/AMDGPUExt/softmax.jl, test/amd/activations.jl, test/amd/batched_mul.jl, test/amd/batched_repr.jl, test/amd/conv.jl, test/amd/pool.jl, test/amd/runtests.jl, test/amd/softmax.jl, test/amd/storage_type.jl, test/runtests.jl
This PR adds AMDGPU extension similar to #445.
Relies on https://github.com/JuliaGPU/AMDGPU.jl/pull/370 and we'd need to tag a new version of AMDGPU.jl for compatibility, so I'll mark it as WIP for now.
For now it has following layers which use MIOpen:
- Convolutions.
- Mean/max pooling.
- Softmax.
- Activations.
Things like pooling **require** passing workspace buffer that was used in forward pass, to the backward pass.
Same for batch normalization, which allows passing computed mini-batch mean & inverse variance to the backward pass to speed-up the computation.
(Although batch norm is not defined in this package).
Therefore I've defined rrules for it as follows.
I decided it is much simpler than introducing some global caching for workspaces.
```julia
function rrule(::typeof(maxpool), …
```
=> Add AMDGPU extension

src/attention.jl, test/amd/attention.jl, test/amd/dropout.jl, test/amd/runtests.jl, test/attention.jl, test/runtests.jl
- Add tests for dropout & attention for AMDGPU extension.
- Add more detailed error messages. Instead of saying that, for example, batch size is incorrect we can also print the values itself, since this is the natural next question.
- Minor refactor (remove trailing spaces).
=> Add dropout & attention tests for AMDGPU

Project.toml, docs/src/reference.md, ext/AMDGPUExt/conv.jl, test/amd/conv.jl
MIOpen only [supports](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/convolution.html) cross-correlation as its convolution.
To perform regular convolution we can reverse the kernel along first two dimensions (for 2D conv).
Doing this every time during `NNlib.conv` calls is expensive, therefore on NNlib level a user will need to manually flip convolution kernel before passing it as an argument.
On the Flux level this will be handled automatically during `Flux.gpu(conv)` conversion once.
Flux's part is done in this PR: https://github.com/FluxML/Flux.jl/pull/2189
- Bump AMDGPU compat, since it has important performance optimizations.
=> Allow regular convolution for AMDGPU

src/dim_helpers/ConvDims.jl, src/gemm.jl
Currently NNlib threaded functions fail if julia is sstarted with > 0 threads in the `:interactive` threadpool.
Here julia had `-t2,1`
```
BoundsError: attempt to access 196608×9×2 Array{Float32, 3} at index [1:196608, 1:9, 3]
Stacktrace:
[1] throw_boundserror(A::Array{Float32, 3}, I::Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Int64})
@ Base ./abstractarray.jl:744
[2] checkbounds
@ ./abstractarray.jl:709 [inlined]
[3] view
@ ./subarray.jl:177 [inlined]
[4] macro expansion
@ ~/.julia/packages/NNlib/Jmwx0/src/impl/conv_im2col.jl:49 [inlined]
[5] (::NNlib.var"#1110#threadsfor_fun#635"{NNlib.var"#1110#threadsfor_fun#634#636"{Array{Float32, 3}, Float32, Float32, SubArray{Float32, 5, Array{Float32, 5}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, …
```
=> Fix nthreads on 1.9 (failure in the presence of interactive threads)

src/impl/conv_im2col.jl, src/impl/depthwiseconv_im2col.jl
The previous `threadid`-based buffering may have been susceptible to error due to task migration.
=> move from bad thread-local to task-local

.buildkite/pipeline.yml, Project.toml, test/ext_amdgpu/dropout.jl, test/runtests.jl
- Don't use artifacts in CI, since 0.5 requires ROCm 5.3+ for which there are no artifacts available.
=> Update AMDGPU compat to 0.5

src/impl/conv_direct.jl, test/conv.jl
=> nonzero beta + flipkernel bugfix

docs/src/reference.md, ext/NNlibCUDACUDNNExt/conv.jl, src/conv.jl, test/ext_cuda/conv.jl, test/ext_cuda/test_utils.jl
Addresses #510 using the same method as in Pytorch (Gauss's trick, complex conv via 3 real convs).
=> cudnn complex convolution via gauss trick

.github/workflows/BenchmarkTrigger.yml
Theoretically, this new workflow can trigger the Benchmark workflow defined in FluxMLBenchmarks.jl.
=> Add a new workflow to trigger the benchmark workflow

docs/src/reference.md, src/NNlib.jl, src/bias_act.jl, src/dropout.jl, src/utils.jl, test/bias_act.jl, test/runtests.jl
This was part of #346, but the conv part got complicated.
Intended as a better alternative to part of https://github.com/FluxML/Flux.jl/pull/2137 --- using this in layers will remove all `identity.(x .+ false)` broadcasts, with less repetition of the idea.
Dismayed how long the `rrule` code is here. I couldn't see what's wrong with the second case (it fails on `swish`) so I commented it out for now. There's room to improve this once https://github.com/JuliaDiff/ChainRulesCore.jl/pull/592 works. 
Some min times are slower. But mean times show the effect of saving allocations.
<details>
```julia
julia> w, b = rand(Float32, 100, 10000), rand(Float32, 100);
julia> @btime bias_act!(relu, $w, $b);
min 19.500 μs, mean 21.375 μs (0 allocations)
julia> @btime relu.($w .+ $b);
min 17.208 μs, mean …
```
=> Add `bias_act!`

Project.toml
=> Bump AMDGPU compat to 0.6

src/impl/conv_im2col.jl, src/impl/depthwiseconv_im2col.jl, test/conv.jl
Fixes https://github.com/FluxML/NNlib.jl/issues/538
Required for https://github.com/FluxML/NNlib.jl/pull/536
=> Fix grad conv im2col

.buildkite/pipeline.yml
If it is alright, I'd like to disable CPU tests on AMD GPU CI machines.
AFAIK, there's only one CI machine right now available for AMD GPUs.
Having it run tests that take ~1 hour increases CI queue significantly.
I've enabled CPU tests on CUDA CI machines, which we have a lot more.
=> Don't run CPU tests on AMDGPU CI machines

src/scatter.jl, test/runtests.jl, test/scatter.jl
- Allow non-`Int64` indices in scatter by promoting them to `Int64` inside the kernel.
This is especially useful when performing reduction over big arrays into a few bins.
Indices can be of `Int8` type, saving a lot of space.
- Fix typo in `Test_Enzyme`. I guess the intention was to disallow any Julia 1.10 version.
```julia
julia> v"1.10.0-beta2" <= v"1.10"
true
julia> v"1.10.0-beta2" <= v"1.10-"
false
```
=> Allow non-Int64 indices in scatter

src/activations.jl
Otherwise diffing with Zygote is type unstable. This is causing all but one of the test failures on stable CI, see https://buildkite.com/julialang/nnlib-dot-jl/builds/1174.
=> Add rrule for `oftf`

.github/workflows/Downstream.yml, .github/workflows/ci.yml
This does everything automatically for us and should speed up CI times. The julia-buildpkg option even warns about this, see e.g. https://github.com/FluxML/NNlib.jl/actions/runs/7492256201.
=> Use julia-actions/cache

Project.toml, docs/src/reference.md, src/NNlib.jl, src/rotation.jl, test/rotation.jl, test/runtests.jl
Hi,
based on  [DiffImageRotation.jl](https://github.com/roflmaostc/DiffImageRotation.jl) and as discussed in #552 I tried to add image rotation into NNlib.jl.
Some comments:
I always assumed a 4D array. In principle, the results match the ones from  [ImageTransformations.jl](https://github.com/JuliaImages/ImageTransformations.jl) closely. But, the boundary handling is different and sometimes rounding artifacts occur.
I compared this a little but I think there is space for interpretation how to do it. There is some code left, to change the boundary handling at the cost of ~20% performance.
@maxfreu mentioned something about different parallelization schemes for CPU vs GPU.
Benchmarking between my implementation and the parallelized elementwise application shows that the timings are roughly …
=> Add image rotation

ext/NNlibCUDAExt/ctc.jl
It looks like CUDA CI is broken here. As I wanted to test NNlib.jl for upcoming cuDNN.jl changes (and possibly add the package to CUDA.jl's reverse-CI), I had a quick look, and for whatever reason inlining this method fixes the compilation error:
```
ctc-gpu: Error During Test at /var/lib/buildkite-agent/builds/gpuci-10/julialang/nnlib-dot-jl/test/ext_cuda/ctc.jl:19
Got exception outside of a @test
InvalidIRError: compiling MethodInstance for NNlibCUDAExt.compute_beta_and_grad_kernel(::CuDeviceMatrix{Float64, 1}, ::Int64, ::Int64, ::Int64, ::CuDeviceVector{Int64, 1}, ::CuDeviceMatrix{Float64, 1}, ::CuDeviceMatrix{Float64, 1}, ::CuDeviceMatrix{Float64, 1}, ::CuDeviceMatrix{Float64, 1}, ::CuDeviceMatrix{Float64, 1}, ::Int64, ::Float64) resulted in invalid LLVM IR
Reason: unsupported call to …
```
=> CUDA: Fix compilation failure.

src/attention.jl
Only minor typo fix in an error message displaying wrong sizes of attention keys and values.
=> Fix typo in dot product attention error message

src/softmax.jl
A slight type instability causes this failure with Enzyme:
```julia
julia> using NNlib, Enzyme
julia> Enzyme.gradient(Reverse, x -> sum(abs2, softmax(x)), randn(3,4))  # Float64 is fine
3×4 Matrix{Float64}:
-0.122783   0.0819441   0.197442   -0.123512
-0.109191  -0.0401521  -0.0706376  -0.0803758
0.231975  -0.041792   -0.126805    0.203887
julia> gradient(Reverse, x -> sum(abs2, softmax(x)), randn(Float32, 3,4))
Illegal updateAnalysis prev:{[-1]:Pointer, [-1,0]:Float@float} new: {[-1]:Pointer, [-1,0]:Integer, [-1,1]:Integer, [-1,2]:Integer, [-1,3]:Integer, [-1,4]:Integer, [-1,5]:Integer, [-1,6]:Integer, [-1,7]:Integer}
val:   %ifelse_result = select i1 %ifelse_cond419, i64 addrspace(11)* %.0.sroa_cast, i64 addrspace(11)* %.0.sroa_cast3, !dbg !562 origin=  %unbox429 = load i64, i64 …
```
=> Make `softmax` Enzyme-friendly

src/NNlib.jl
I think we should have added the export for \nabla imrotate in  #553?
=> Add export for imrotate gradient

ext/NNlibCUDACUDNNExt/batchnorm.jl, test/ext_cuda/batchnorm.jl
In test mode, the CUDA cuDNN implementation of batchnorm was not matching the CPU batchnorm in FLUX. In FLUX, with track_stats=False, the mean and variance of the current batch are used. Here, mean and variance were initialized to 0 and 1, respectively, and passed to cudnnBatchNormalizationForwardInference.
To fix this, we need to calculate the mean and variance over the current batch to match the CPU implementation. Unfortunately, cudnnBatchNormalizationForwardInference requires a trained running mean and variance. However, batchnorm train and test should be identical without tracked stats since they both normalize over the current batch. As a result we can use cudnnBatchNormalizationForwardTraining in test mode as well, which works without a running mean and variance.
This is needed to …
=> Fix batchnorm in testmode without track stats

ext/NNlibEnzymeCoreExt/NNlibEnzymeCoreExt.jl, test/conv.jl
Add enzyme rule for missing conv utilities
Fixes https://github.com/FluxML/NNlib.jl/issues/565
=> Enzyme: add derivatives for ∇conv_filter and ∇conv_data

src/NNlib.jl, src/gemm.jl
This change is in support of https://github.com/JuliaLang/julia/pull/50699
=> Transition to `LinearAlgebra.BLAS.libblastrampoline` instead of `Base.libblas_name`

src/sampling.jl, src/upsample.jl
- Use GPU-friendly rounding.
Otherwise we create boxed value that is used for reporting exceptions which triggers hostcalls on AMDGPU.
- Use `Int` for indexing (as it is default anyway) instead of converting to `UInt32`.
Fixes #573.
=> Use GPU-friendly rounding

src/padding.jl
Current version of `pad_reflect` causes input array to be copied to host during backpropagation because of [this rule](https://github.com/JuliaDiff/ChainRules.jl/blob/2db48540b2fd9943c4e6db92dba1ee1e8f7f8550/src/rulesets/Base/indexing.jl#L183).
Instead of usign `StepRange` we should use `UnitRange` for `selectdim` and `reverse`, this avoids expensive copying.
```julia
julia> using Revise, CUDA, Zygote
julia> x = CuArray(rand(Float32, 8000, 1));
julia> Δ = CuArray(ones(Float32, 1, 1));
julia> y, back = Zygote.pullback(x) do x
sum(NNlib.pad_reflect(x, (0, 10)); dims=(1, 2))
end;
julia> back(Δ);
D to H copy CuArray{Float32, 2, CUDA.DeviceMemory}: (8000, 1) -> Matrix{Float32}: (8000, 1)
D to H copy CuArray{Float32, 2, CUDA.DeviceMemory}: (11, 1) -> Matrix{Float32}: (11, 1)
```
Besides copying …
=> Fix padding causing device to host copies

src/impl/conv_direct.jl, test/conv.jl
Closes #490, #405.
As described in #490, undefined array elements can't be indexed on all datatypes:
```Julia-repl
julia> v1 = Array{Float32}(undef, 3)
3-element Vector{Float32}:
2.7761215f-21
1.0f-45
2.7765319f-21
julia> v2 = Array{Set}(undef, 3)
3-element Vector{Set}:
#undef
#undef
#undef
julia> v1[1] # works
2.7761215f-21
julia> v2[1] # doesn't work
ERROR: UndefRefError: access to undefined reference
Stacktrace:
[1] getindex(A::Vector{Set}, i1::Int64)
@ Base ./essentials.jl:13
[2] top-level scope
@ REPL[34]:1
```
Such indexing is used in the right-hand side of `conv_direct!` on main
https://github.com/FluxML/NNlib.jl/blob/627374ca51090c4e5b9cfbed5c15bdaa992891f8/src/impl/conv_direct.jl#L111
which means that `conv_direct!` doesn't support all input datatypes.
However, assignments work, …
=> Support `conv_direct!` on custom datatypes

src/activations.jl, test/ext_cuda/activations.jl
Without this the following errors on 1.10
```julia
using CUDA, NNlib
x = cu(rand(Float32, 10, 10))
b = cu(rand(Float32, 10, 10))
f = sigmoid_fast ∘ +
f.(x, b)
f = swish ∘ +
f.(x, b)
```
<details>
<summary>Error</summary>
```julia
ERROR: InvalidIRError: compiling MethodInstance for (::GPUArrays.var"#35#37")(::CUDA.CuKernelContext, ::CuDeviceMatrix{Float32, 1}, ::Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{…}, Tuple{…}, ComposedFunction{…}, Tuple{…}}, ::Int64) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to var"#_#103"(kw::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}}, c::ComposedFunction, x...) @ Base operators.jl:1041)
Stacktrace:
[1] ComposedFunction
@ ./operators.jl:1041
[2] …
```
=> fix: remove inlining of sigmoid_fast pre 1.11-

.github/workflows/Downstream.yml
- removes 3 packages. they were last updated more than 2 years back and don't even support latest NNlib, so no point in spawning those jobs.
- Lux uses ReTestItems.jl so I added some of the env vars that allow parallel testing.
=> ci: update downstream testing

docs/src/reference.md, src/activations.jl, src/audio/mel.jl, src/audio/stft.jl, src/ctc.jl, src/dim_helpers/DepthwiseConvDims.jl, src/dim_helpers/PoolDims.jl, src/dropout.jl, src/pooling.jl, src/softmax.jl, src/utils.jl
- Added syntax highlighting tags for fenced code blocks (`julia-repl`)
- Fixed minor typos (re: backticks)
- Fixed `note` admonition block
- Added titles to URLs (links to Wikipedia for references)
The applicable test for this is to build it using Documenter.jl and review, and that testing has been performed.
=> Update method docstrings

Project.toml
Keep 0.1 compat as no previously-released functionality has been changed.
See [release notes](https://github.com/JuliaConcurrent/Atomix.jl/releases/tag/v1.0.0) and https://github.com/JuliaGPU/KernelAbstractions.jl/pull/545 for more details.
Depends on https://github.com/JuliaGPU/KernelAbstractions.jl/pull/545
=> Add Atomix.jl v1 compat

src/audio/spectrogram.jl, test/testsuite/spectral.jl
With `power > 0` gradient will become `NaN` where spectrogram is `~0` (because of singularity at `abs(0)`).
Adding small epsilon fixes this issue (and the results match pytorch).
```julia
x = gpu(ones(Float32, 1024, 1, 1))
window = gpu(hann_window(1024)))
l, g = Zygote.withgradient(x) do x
sum(spectrogram(x; n_fft=1024, hop_length=256, power=2.0, window)
end
```
=> Fix `NaN` gradient in spectrogram

src/bias_act.jl
This change should be harmless on Julia 1.10 and 1.11, but fix an error on 1.12. It's an internal function so we did sign up to fix things as needed.
```
julia> VERSION
v"1.10.7"
julia> Core.Compiler.return_type(sin, Tuple{Int})
Float64
julia> Core.Compiler._return_type(sin, Tuple{Int})
Float64
```
```
julia> VERSION
v"1.11.2"
julia> Core.Compiler.return_type(sin, Tuple{Int})
Float64
julia> Core.Compiler._return_type(sin, Tuple{Int})
Float64
```
Master:
```
julia> VERSION
v"1.12.0-DEV.1731"
julia> Core.Compiler.return_type(sin, Tuple{Int})
Float64
julia> Core.Compiler._return_type(sin, Tuple{Int})
ERROR: MethodError: no method matching _return_type(::typeof(sin), ::Type{Tuple{Int64}})
You may have intended to import Base._return_type
The function `_return_type` exists, but no method is …
```
=> Use `return_type` not `_return_type` to fix an error on nightly

Project.toml, src/conv.jl
Aims to fix errors like this in CI, from Zygote 0.7:
```
AutoDiff: spatial_rank=3: Error During Test at /home/runner/work/Zygote.jl/Zygote.jl/downstream/test/conv.jl:889
Got exception outside of a @test
MethodError: no method matching length(::InplaceableThunk{Thunk{ChainRules.var"#719#722"{Float64, Colon, Array{Float64, 5}, ProjectTo{AbstractArray, @NamedTuple{element::ProjectTo{Float64, @NamedTuple{}}, axes::NTuple{5, Base.OneTo{Int64}}}}}}, ChainRules.var"#718#721"{Float64, Colon}})
The function `length` exists, but no method is defined for this combination of argument types.
You may need to implement the `length` method or define `IteratorSize` for this type to be `SizeUnknown`.
Closest candidates are:
length(::JSON.Parser.MemoryParserState)
@ JSON …
```
=> Add unthunk in conv.jl

ext/NNlibCUDAExt/sampling.jl, src/bias_act.jl, src/sampling.jl, test/ext_cuda/sampling.jl, test/sampling.jl
[Current `grid_sampling` function only accept 4D input, which is suitable for 2D images. Adding function for 5D input to support 3D images.]
=> Add Grid Sampling for 3D images.
