FluxML/NNlib.jl

src/NNlib.jl, src/activation.jl
Ref: [Swish: a Self-Gated Activation Function](https://arxiv.org/pdf/1710.05941.pdf)
=> act: Swish, a self-gated activation function

REQUIRE, deps/build.jl, src/NNlib.jl, test/activation.jl
=> Pre-built binaries

src/NNlib.jl, src/logsoftmax.jl, test/runtests.jl
Adding `logsoftmax` function by following the convention of `softmax`.
=> Adding logsoftmax

src/cubroadcast.jl, test/cubroadcast.jl, test/runtests.jl
Allows @fix to be used in more complex expressions.
=> Use let in @fix #37

src/impl/pool.jl
=> [Julia 0.7] Maxpool depwarns

src/conv.jl, src/impl/conv.jl, test/conv.jl
Adds support for Depthwise Convolutions. #41
=> Depthwise Convolutions

src/impl/conv.jl, test/conv.jl
I have updated the gradient definition for the filter. The tests were not able to catch this case. So I have updated the tests to handle all the cases.
=> Fix Depthwise Convolutions

src/conv.jl
Added the flipkernel argument from `conv_data` and `conv_filter` family of functions.
=> Expose flipkernel argument

.travis.yml, appveyor.yml
Enable coverage and turn on badge on README
=> Enable coverage

src/activation.jl
=> Make logσ(x) = -softplus(-x)

src/impl/conv_im2col.jl, src/impl/depthwiseconv_im2col.jl
Closes https://github.com/FluxML/NNlib.jl/issues/96
=> Preserve pointers before sending them into `gemm!()`

src/nnpack/impl.jl
=> NNPACK Convolution Patch

Manifest.toml, Project.toml, src/NNlib.jl, src/conv.jl, src/impl/conv_direct.jl, src/impl/conv_im2col.jl, src/impl/depthwiseconv_direct.jl, src/impl/depthwiseconv_im2col.jl, src/nnpack/impl.jl, src/nnpack/interface.jl, src/pooling.jl, test/inference.jl, test/runtests.jl
@staticfloat I am removing the TimerOutputs given they mess with the type inference. Let me know if there are any other possible solutions to this issue
Fixes #125
=> Remove timer outputs as they mess with type inference

src/impl/pooling_direct.jl, test/pooling.jl
=> Fix typo in `maxpool` backprop

src/dim_helpers/ConvDims.jl, src/impl/conv_im2col.jl, src/impl/depthwiseconv_im2col.jl
Fixes https://github.com/FluxML/NNlib.jl/issues/158
=> Use a thread-sharded `col` in `im2col`-related functions

src/activation.jl, test/activation.jl
Referring to issue - [144](https://github.com/FluxML/NNlib.jl/issues/144)
=> Added Mish activation

src/activation.jl, test/activation.jl
added some activation functions and unit tests for the same.
Tests passed for all cases except the gradient check in the softshrink activation function.
=> Activation functions added

src/activation.jl, src/dim_helpers/ConvDims.jl
I have cleaned up the docstrings and definitions of the activation functions, and fixed a missing comma in Base.show for ConvDims.
=> docstring, type annotation

test/batchedmul.jl
Added tests to ensure that the BatchedAdjOrTrans lazy wrapper correctly interfaces with Base.
=> BatchedAdjOrTrans interface tests

src/conv.jl
just moving around code and adding some comments on the convolutions' processing steps
=> dev comments for conv

src/softmax.jl
=> Fix presumed copy-paste error in generic fmaximum

src/NNlib.jl, src/conv_bias_act.jl
Required for:
https://github.com/JuliaGPU/CUDA.jl/pull/321
=> Added wrapper for convolution, bias, and activation

src/conv_bias_act.jl, test/conv_bias_act.jl, test/runtests.jl
fix #243 
Side note: we don't have the adjoint for `conv_act_bias`
cc @gartangh
=> fix conv_act_bias

Project.toml, src/NNlib.jl, src/chainrulescore.jl, src/deprecations.jl, src/softmax.jl, test/runtests.jl, test/softmax.jl, test/test_utils.jl, test/zygote.jl
=> new API grad softmax

Project.toml, src/batched/batchedmul.jl, src/gemm.jl, test/pooling.jl, test/test_utils.jl
and add more comments about where Compat.jl is actually being used.
=> Partially revert #259

src/dim_helpers/DenseConvDims.jl, test/inference.jl
This change fixes the errors from my examples in https://github.com/FluxML/Flux.jl/issues/1350#issuecomment-765348942.
Solution taken from https://github.com/FluxML/NNlib.jl/issues/274#issuecomment-773129949.
=> Force return type of channels_in and channels_out

src/upsample.jl, test/upsample.jl
follow up to discussion in https://github.com/FluxML/Flux.jl/pull/1468
=> add size keyword to upsample_nearest

src/softmax.jl, test/softmax.jl
Closes #206
When I try to time it, this check costs about 1% when everything is finite, which seems completely fine.
=> Make softmax understand `Inf`

.github/workflows/ci.yml, Project.toml, src/padding.jl, test/padding.jl
=> Add some user forwards

src/batched/batchedadjtrans.jl, src/batched/batchedmul.jl, test/batchedmul.jl
=> Fix batched_mul gradient, for cases with one matrix

Project.toml, src/gather.jl, src/scatter.jl, test/gather.jl, test/scatter.jl
=> unexport gather/scatter

src/activations.jl
- add more efficient but still numerically stable version
- add rrule
=> revisit softplus

src/utils.jl
Resolve issue for FluxML/NNlibCUDA.jl#13.
=> Make reverse_indices gpu compatible

Project.toml, src/scatter.jl, test/runtests.jl, test/scatter.jl
Add a destination size hint for scatter + fix scatter rrule not accepting the keyword args + slim down a bit the tested types
=> dstsize for scatter

Project.toml, src/batched/batchedadjtrans.jl, src/batched/batchedmul.jl, src/conv.jl, src/gather.jl, src/padding.jl, src/pooling.jl, src/scatter.jl, src/softmax.jl, src/upsample.jl, test/scatter.jl, test/softmax.jl, test/test_utils.jl
And bump ChainRules* to 1.x
supersedes #338 
cc @oxinabox
=> Add generic fallbacks for rrules not expecting Thunks

src/batched/batchedmul.jl, test/batchedmul.jl
fixes https://github.com/FluxML/NNlib.jl/issues/333
=> export batched_mul!

Project.toml, src/activations.jl, src/padding.jl, src/softmax.jl, src/upsample.jl, test/runtests.jl
This loads Documenter to run tests in docstrings locally. They are probably tested as part of Flux's documentation step, but better to find out sooner if something needs fixing.
=> Run `jldoctests`

src/NNlib.jl, src/functions.jl, test/functions.jl, test/runtests.jl
GLU  from "Language Modeling with Gated Convolutional Networks" Dauphin et al. 2017
=> Add Gated Linear Unit (GLU)

src/activations.jl
=> Make ACTIVATIONS vector constant.

.github/workflows/Downstream.yml
Fixes #374. Repo suggestions welcome, for now I've excluded anything that also has a dep on Flux.
=> Add downstream reverse CI

.buildkite/pipeline.yml
=> Add codecov token secret

src/NNlib.jl, src/activations.jl, src/batched/batchedadjtrans.jl, src/batched/batchedmul.jl, src/conv.jl, src/conv_bias_act.jl, src/dim_helpers/ConvDims.jl, src/dim_helpers/DenseConvDims.jl, src/dim_helpers/DepthwiseConvDims.jl, src/dim_helpers/PoolDims.jl, src/functions.jl, src/gemm.jl, src/impl/conv_direct.jl, src/impl/pooling_direct.jl, src/padding.jl, src/pooling.jl, src/sampling.jl, src/softmax.jl, src/upsample.jl
An attempt at implementing #394
=> Move exports to main source file

src/upsample.jl
This PR gets rid of some duplicate code which can be avoided simply by using dispatch on the different array dimensions. I think some sort of this was in discussion with @mcabbott when the initial code was written; I hope this improves things. Apart from that, I moved the `@inbounds` macro back into the threads scope, because it does not penetrate the `@threads` macro. The changes in the diff look bigger than they actually are, because I shifted some code up and down.
There is a corresponding PR in https://github.com/FluxML/NNlibCUDA.jl/pull/49 which can be merged synchronously. This is another case, where a subpackage would be nice, also for more stable CI.
=> boil down upsampling code via dynamic dispatch

.github/workflows/Downstream.yml, .github/workflows/ci.yml, .github/workflows/clean_preview.yml
About FluxML/Flux.jl#1939 & FluxML/Flux.jl#2170
* Add the same condition of coverage generation like Zygote.jl and Flux.jl
* Replace deprecated actions.
=> Update deprecated actions & change coverage upload entry

.github/workflows/Downstream.yml
=> Add downstream tests for Lux.jl

.github/workflows/BenchmarkTrigger.yml
=> Fix BenchmarkTrigger.yml

.buildkite/pipeline.yml, Project.toml
Also bump AMDGPU CI to Julia 1.10. Since CI has Navi 3 now, which works only on 1.10+.
=> Bump AMDGPU compat to 0.8

src/padding.jl, test/padding.jl
It fixes the issue #555 where we need to convert Int type dimension to a Tuple
=> Fixes #555

ext/NNlibCUDACUDNNExt/conv.jl
=> Update the activation inplace for cudnn

src/softmax.jl
Similar to https://github.com/FluxML/NNlib.jl/pull/569
Needed for https://github.com/FluxML/Flux.jl/issues/2443
@CarloLucibello
=> Type stabilize logsoftmax

src/batched/batchedmul.jl
=> fix typos in the doc for batched_mul!

ext/NNlibAMDGPUExt/activations.jl, test/ext_amdgpu/activations.jl
See failure without the patch https://buildkite.com/julialang/nnlib-dot-jl/builds/1394#0190be92-4c29-4fd6-8bf0-5c02065f9304/277-655
=> fix: MIOpen only supports activations till dimension 5

src/activations.jl
This should fix https://github.com/FluxML/NNlib.jl/issues/631.
- ~~[ ] Tests are added~~
- ~~[ ] Documentation, if applicable~~
=> Add type alias for gelu -> gelu_tanh

src/dim_helpers/ConvDims.jl, src/gemm.jl
=> Use the correct `nthreads`
